#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  branches:
    '{develop}':
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
    '{master}':
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Chromatic Publish
            script:
              - npx chromatic --project-token=3b67b6c2ac82 --auto-accept-changes
            caches:
              - node
