#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:14.17.0

pipelines:
  branches:
    '{develop}':
        - step:
            name: Build, Test and Chromatic Publish
            caches:
              - node
            script:
              - npm install
              - npm test -- -u
              - npx chromatic --project-token=5715d8611200 --auto-accept-changes
    '{master}':
        - step:
            name: Build, Test and Chromatic Publish
            caches:
              - node
            script:
              - npm install
              - npm test -- -u
              - npx chromatic --project-token=5715d8611200 --auto-accept-changes
